{
  inputs,
  pkgs,
  homeLib,
  ...
}:

{
  home.packages = with pkgs; [
    bat
    bun
    claude-code
    codex
    ffmpeg-full
    homeLib.wrappedOpencode
    inputs.t3code.packages.${pkgs.stdenv.hostPlatform.system}.t3code-nightly
    skills
    homeLib.zellijNewTabZoxide
    homeLib.zellijSyncTabName
    fd
    btop
    fastfetch
    gh
    hyfetch
    jq
    mkp224o
    nixfmt
    difftastic
    ripgrep
    tea
    trash-cli
    tree
    unzip

    rust-analyzer
    typescript-language-server
    nil

    element-desktop
    file-roller
    font-manager
    foliate
    gimp3
    google-chrome
    handbrake
    inkscape
    kdePackages.kdenlive
    libreoffice
    logseq
    obs-studio
    pavucontrol
    prismlauncher
    qpwgraph
    qbittorrent-enhanced
    signal-desktop
    slack
    tor-browser
    vesktop
    vlc
    zulip
    linphone
    lmstudio
    homeLib.betterbird
    brightnessctl
    nautilus
    playerctl
    wl-clipboard
    xdg-utils

    gnomeExtensions.appindicator
    gnomeExtensions.auto-move-windows
    gnomeExtensions.clipboard-indicator
    gnomeExtensions.emoji-copy
    gnomeExtensions.hide-top-bar
    gnomeExtensions.maximized-by-default-actually-reborn
    gnomeExtensions.no-titlebar-when-maximized
    gnomeExtensions.system-monitor-next
    gnomeExtensions.tailscale-qs
    gnomeExtensions.wifi-qrcode

    nerd-fonts.commit-mono
  ];
}
