# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ae39dec6-3a9a-4822-9b46-a71f776dca5d";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ae39dec6-3a9a-4822-9b46-a71f776dca5d".device = "/dev/disk/by-uuid/ae39dec6-3a9a-4822-9b46-a71f776dca5d";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/82A5-BE9B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f224835a-588d-4ad4-921c-a73e952da0ea"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
